import "../../../components/header-prod/header-prod";
import "../../../components/footer-prod/footer-prod";
import "../../../components/booking/booking";
import "../../../components/icon-list/icon-list";
import "../../../components/review-list/review-list";
import "../../../components/bullet-list/bullet-list";
import("../../../components/doughnut-chart/doughnut-chart");
import "normalize.css";
import "../../../index.scss";
import "./roomDetails.scss";
